app = "fly-monitoring"
primary_region = "ams"

[build]
dockerfile = "./Dockerfile"

[env]
GF_SECURITY_ADMIN_PASSWORD = "admin"
GF_SERVER_HTTP_PORT = "3000"


[[services]]
  internal_port = 3000
  protocol = "tcp"
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
