app = "fly-monitoring"
primary_region = "ams"

[build]
dockerfile = "./Dockerfile"

[env]
GF_SECURITY_ADMIN_PASSWORD = "admin"
GF_SERVER_HTTP_PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 9090
  protocol = "tcp"
  [[services.ports]]
    port = 9090

[[services]]
  internal_port = 9093
  protocol = "tcp"
  [[services.ports]]
    port = 9093
