app = "fly-monitoring"
primary_region = "ams"

[build]
dockerfile = "./Dockerfile"

[env]
GF_SECURITY_ADMIN_PASSWORD = "admin"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
