global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'my-microservices'
    metrics_path: /health
    static_configs:
      - targets:
          - 'your-api1.fly.dev'
          - 'your-api2.fly.dev'
